import setuptools

setuptools.setup(
    name='sprockets.mixins.statsd',
    version='1.3.0',
    description='Handler mixins for automated metric reporting',
    long_description=open('README.rst').read(),
    url='https://github.com/sprockets/sprockets.mixins.statsd.git',
    author='AWeber Communications',
    author_email='api@aweber.com',
    license=open('LICENSE').read(),
    classifiers=[
        'Development Status :: 4 - Beta',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: BSD License',
        'Natural Language :: English',
        'Operating System :: OS Independent',
        'Programming Language :: Python :: 2',
        'Programming Language :: Python :: 2.6',
        'Programming Language :: Python :: 2.7',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.2',
        'Programming Language :: Python :: 3.3',
        'Programming Language :: Python :: 3.4',
        'Programming Language :: Python :: Implementation :: CPython',
        'Programming Language :: Python :: Implementation :: PyPy',
        'Topic :: Software Development :: Libraries',
        'Topic :: Software Development :: Libraries :: Python Modules'
    ],
    packages=['sprockets',
              'sprockets.mixins',
              'sprockets.mixins.statsd'],
    package_data={'': ['LICENSE', 'README.md']},
    include_package_data=True,
    namespace_packages=['sprockets',
                        'sprockets.mixins'],
    install_requires=open("requirements.txt").read(),
    zip_safe=False)
